name: macOS Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ main ]

jobs:
  macos-build:
    name: macOS Build
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Display build information
        run: |
          echo "🖥️ Building CEF for macOS"
          echo "Generator: Unix Makefiles (default)"
          echo "Architecture: $(uname -m)"
          echo "macOS version: $(sw_vers -productVersion)"
          echo "Available disk space: $(df -h . | tail -1 | awk '{print $4}')"
      
      - name: Check network connectivity
        run: |
          echo "Testing network connectivity to CEF builds..."
          curl -I https://cef-builds.spotifycdn.com/ || echo "Direct connection failed, but this is expected"
          echo "Network test completed"
      
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27.9'
      
      - name: Configure
        run: cmake -B build -S . -DCEF_ROBUST_DOWNLOAD=ON
      
      - name: Build
        run: cmake --build build --config Release --target cef_sanity_test
      
      - name: Run CEF sanity test
        run: ./build/test/cef_sanity_test
      
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cef-build-macos-${{ github.sha }}
          path: |
            build/test/cef_sanity_test
          retention-days: 7
