name: macOS Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  macos-build:
    name: macOS Build
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Display build information
        run: |
          echo "í½Ž Building CEF for macOS"
          echo "Generator: Unix Makefiles (default)"
      
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27.9'
      
      - name: Configure
        run: cmake -B build -S .
      
      - name: Build
        run: cmake --build build --config Release --target cef_sanity_test
      
      - name: Run CEF sanity test
        run: ./build/test/cef_sanity_test
      
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cef-build-macos-${{ github.sha }}
          path: |
            build/test/cef_sanity_test
          retention-days: 7
