name: Windows Build

on:
  push:
    branches: ['**']
  pull_request:
    branches: [ main ]

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Display build information
        run: |
          echo "🪟 Building CEF for Windows"
          echo "Generator: Visual Studio 17 2022"
          echo "Architecture: $env:PROCESSOR_ARCHITECTURE"
          echo "Windows version: $(Get-WmiObject -Class Win32_OperatingSystem | Select-Object -ExpandProperty Caption)"
          echo "Available disk space: $((Get-PSDrive C | Select-Object -ExpandProperty Free) / 1GB) GB"
        shell: powershell
      
      - name: Check network connectivity
        run: |
          echo "Testing network connectivity to CEF builds..."
          curl -I https://cef-builds.spotifycdn.com/ || echo "Direct connection failed, but this is expected"
          echo "Network test completed"
        shell: bash
      
      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.27.9'
      
      - name: Configure
        run: cmake -B build -S . -G "Visual Studio 17 2022" -DCEF_ROBUST_DOWNLOAD=ON
        shell: bash
      
      - name: Build all tests
        run: cmake --build build --config Release
        shell: bash
      
      - name: Run all CEF tests with CTest
        run: cd build/test && ctest -C Release --verbose
        shell: bash
      
      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cef-build-windows-${{ github.sha }}
          path: |
            build/test/**/*test*
          retention-days: 7
